- name: Send Php-Config File
  copy:
    src: www.conf
    dest: /etc/php-fpm.d/

- name: Send nginx config file
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  loop: "{{ file_name }}"