- name: unarchive code
  unarchive:
    src: "{{ item }}"
    dest: /website/
    owner: "{{ str_www }}"
    group: "{{ str_www }}"
    remote_src: yes
  with_items:
    - /tmp/wp.tar.gz
    - /tmp/zh.tar.gz
  notify: Restart nginx_php Server
  ignore_errors: yes